name: Build

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: macos-26

    steps:
      - uses: actions/checkout@v4
      - name: Build
        run: xcodebuild build -project Nola.xcodeproj -scheme Nola -destination 'platform=macOS' CODE_SIGNING_ALLOWED=NO
